# Generated by Django 3.0.4 on 2020-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaTracks', '0004_state_k_recovered'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_k',
            name='lastupdate',
            field=models.CharField(default='Now', max_length=200),
        ),
    ]
