# Generated by Django 3.0.4 on 2020-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaTracks', '0005_state_k_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_k',
            name='district_present',
            field=models.BooleanField(default=False),
        ),
    ]
