# Generated by Django 3.0.4 on 2020-04-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaTracks', '0006_state_k_district_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_k',
            name='statecode',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
