# Generated by Django 3.0.4 on 2020-04-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalTracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='city',
            old_name='provice',
            new_name='province',
        ),
    ]
