# Generated by Django 3.0.4 on 2020-04-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalTracks', '0002_auto_20200410_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
